source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'sass-rails', github: 'rails/sass-rails', branch: 'master'
gem 'sprockets-rails', github: 'rails/sprockets-rails', branch: 'master'
gem 'sprockets', github: 'rails/sprockets', branch: 'master'

gem 'roadie-rails', :path => '../../..'
